### ISSUE TITLE
Add css-modules support

### ISSUE THREAD

**Issue by kevincastejon** [rwieruch/advanced-react-webpack-babel-setup#4]
is it possible to add css-modules support ?

**Comment by rwieruch** [comment]
Would someone want to open a PR for it? I wouldn't want to integrate it into this repository, but I would use your work as a blueprint to write a tutorial for others about it. The PR would be a great reference for it for other folks interested in this. 🚀

**Comment by arpitbatra123** [comment]
Hey. Can i work on this?

**Comment by rwieruch** [comment]
Sure thing :) Goal: Make the project work with one `style.module.css` which imports `import styles from './style.module.css';` and uses the style in a React component. Thanks for helping out here @arpitbatra123 🚀

**Comment by arpitbatra123** [comment]
I created a PR for this #9. Please Review. Thanks. :)

**Comment by rwieruch** [comment]
https://www.robinwieruch.de/react-css-modules Thank you @arpitbatra123 ❤️
